import { NgModule } from '@angular/core';

import {
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatToolbarModule,
    MatDatepickerModule,
    MatGridListModule,
    MatStepperModule,
    MatNativeDateModule,
    MatIconModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatButtonToggleModule,
    MatDialogModule,
    MatListModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatMenuModule,
    MatTooltipModule,
    MatSnackBarModule
} from '@angular/material';

@NgModule({
    imports: [
        MatInputModule,
        MatSelectModule,
        MatSlideToggleModule,
        MatCheckboxModule,
        MatAutocompleteModule,
        MatProgressBarModule,
        MatToolbarModule,
        MatDatepickerModule,
        MatGridListModule,
        MatStepperModule,
        MatNativeDateModule,
        MatIconModule,
        MatCardModule,
        MatButtonModule,
        MatFormFieldModule,
        MatButtonToggleModule,
        MatDialogModule,
        MatListModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatRippleModule,
        MatMenuModule,
        MatTooltipModule,
        MatSnackBarModule
    ],
    exports: [
        MatInputModule,
        MatSelectModule,
        MatSlideToggleModule,
        MatCheckboxModule,
        MatAutocompleteModule,
        MatProgressBarModule,
        MatToolbarModule,
        MatDatepickerModule,
        MatGridListModule,
        MatStepperModule,
        MatNativeDateModule,
        MatIconModule,
        MatCardModule,
        MatButtonModule,
        MatFormFieldModule,
        MatButtonToggleModule,
        MatDialogModule,
        MatListModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatRippleModule,
        MatMenuModule,
        MatTooltipModule,
        MatSnackBarModule
    ]
})
export class VertiMaterialModule {}
